import Foundation

/// The extended supplement bank — a browsable education library grouped by
/// function (never by demographic: grouping by who-you-are reads as a
/// recommendation, which this deliberately is not — founder decision
/// 2026-08-23). Same hedged-copy rules as `SupplementLibraryData`: "may
/// help support," never "will," never a dose, never a disease claim.
///
/// The Core Six in `SupplementLibraryData` stay separate and on top;
/// nothing here duplicates them.
struct SupplementBankGroup: Identifiable {
    var id: String { name }
    let name: String
    let entries: [SupplementEducationEntry]
}

enum SupplementBankData {
    /// Shared placeholder review date, same convention as the Core Six.
    private static let reviewed = Date(timeIntervalSince1970: 1_735_689_600) // 2025-01-01 placeholder
    private static let defaultConsult = ["You're pregnant or nursing.", "You take prescription medication.", "You're managing a health condition."]
    private static let defaultReminder = "Follow the amount and timing on the product label — CMSN does not set a personalized dose."
    private static let defaultSources = ["NIH Office of Dietary Supplements fact sheet (general reference — verify current version before citing in-app)"]

    private static func e(
        _ id: String, _ name: String, what: String, helps: [String],
        level: EvidenceLevel, forms: [String], cautions: [String],
        consult: [String] = defaultConsult
    ) -> SupplementEducationEntry {
        SupplementEducationEntry(
            id: id, name: name, whatItIs: what, mayHelpSupport: helps,
            evidenceLevel: level, commonForms: forms,
            labelUseReminder: defaultReminder, cautions: cautions,
            consultProfessionalWhen: consult, sourceReferences: defaultSources,
            lastReviewed: reviewed
        )
    }

    static let groups: [SupplementBankGroup] = [
        SupplementBankGroup(name: "Performance", entries: [
            e("beta-alanine", "Beta-Alanine",
              what: "An amino acid that raises muscle carnosine, a buffer against the acid build-up of hard efforts.",
              helps: ["May help support performance in high-intensity efforts lasting one to four minutes.", "May help support training volume in repeated hard sets."],
              level: .moderate, forms: ["Powder", "Capsules"],
              cautions: ["A harmless tingling (paresthesia) is common and fades on its own."]),
            e("citrulline", "Citrulline Malate",
              what: "An amino acid compound involved in nitric-oxide production and blood flow.",
              helps: ["May help support muscular endurance and training volume.", "May help support the muscle 'pump' sensation during lifting."],
              level: .moderate, forms: ["Powder"],
              cautions: ["Mild stomach upset is possible at higher label servings."]),
            e("betaine", "Betaine (Trimethylglycine)",
              what: "A compound found in beets and whole grains, studied for power output.",
              helps: ["May help support power and strength performance in some studies — results are mixed."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["A fishy body odor is a known, harmless side effect for some people."]),
            e("hmb", "HMB",
              what: "A metabolite of the amino acid leucine, studied mostly in new trainees and older adults.",
              helps: ["May help support recovery when training is new or volume jumps sharply.", "Evidence in experienced lifters is weak."],
              level: .limited, forms: ["Capsules", "Powder"],
              cautions: ["Benefits reported in trained athletes are inconsistent across studies."]),
            e("taurine", "Taurine",
              what: "An amino acid abundant in muscle and heart tissue, common in energy drinks.",
              helps: ["May help support endurance performance and reduce exercise-induced muscle soreness in some studies."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["Often bundled with high-caffeine products — check total caffeine separately."]),
            e("sodium-bicarbonate", "Sodium Bicarbonate",
              what: "Baking soda — an extracellular buffer studied for short, very hard efforts.",
              helps: ["May help support repeated sprint and one-to-seven-minute maximal efforts."],
              level: .moderate, forms: ["Powder", "Enteric capsules"],
              cautions: ["Stomach distress is common — many people can't tolerate label servings.", "Meaningful sodium load; relevant if you watch sodium intake."]),
        ]),
        SupplementBankGroup(name: "Recovery & Sleep", entries: [
            e("magnesium", "Magnesium (Glycinate / Citrate)",
              what: "A mineral involved in hundreds of enzyme reactions, including muscle and nerve function.",
              helps: ["May help support sleep quality when intake from food is low.", "May help support normal muscle function."],
              level: .moderate, forms: ["Capsules", "Powder"],
              cautions: ["Some forms (oxide, citrate at higher amounts) can loosen stools."]),
            e("melatonin", "Melatonin",
              what: "A hormone your body makes at night; supplemental forms are studied for sleep timing.",
              helps: ["May help support falling asleep when your schedule shifts (travel, early sessions).", "More about timing than depth of sleep."],
              level: .moderate, forms: ["Tablets", "Gummies"],
              cautions: ["Morning grogginess at higher label servings.", "It is a hormone — many countries regulate it as a medicine."]),
            e("ashwagandha", "Ashwagandha",
              what: "An herb in the adaptogen category, studied for perceived stress and recovery.",
              helps: ["May help support perceived stress and sleep quality in some studies.", "Small studies suggest possible support for strength adaptation."],
              level: .limited, forms: ["Capsules", "Powder"],
              cautions: ["Not well studied long-term.", "Interacts with thyroid and sedative medications."],
              consult: ["You have a thyroid condition.", "You take sedatives or thyroid medication.", "You're pregnant or nursing."]),
            e("glycine", "Glycine",
              what: "A simple amino acid studied at bedtime for sleep quality.",
              helps: ["May help support subjective sleep quality when taken before bed in small studies."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["Evidence base is small."]),
            e("tart-cherry", "Tart Cherry",
              what: "Concentrated Montmorency cherry, studied around hard training blocks.",
              helps: ["May help support recovery from muscle-damaging exercise.", "May help support sleep via natural melatonin content."],
              level: .limited, forms: ["Juice concentrate", "Capsules"],
              cautions: ["Juice forms carry meaningful sugar — check the label."]),
            e("l-theanine", "L-Theanine",
              what: "An amino acid from tea, often paired with caffeine.",
              helps: ["May help support calm focus and take the edge off caffeine jitters."],
              level: .moderate, forms: ["Capsules"],
              cautions: ["Effects are subtle and vary by person."]),
        ]),
        SupplementBankGroup(name: "Joint & Bone", entries: [
            e("collagen", "Collagen Peptides",
              what: "Hydrolyzed structural protein, studied with vitamin C before loading connective tissue.",
              helps: ["May help support joint comfort with consistent use in some studies.", "Not a substitute for complete protein — its amino profile is incomplete."],
              level: .limited, forms: ["Powder"],
              cautions: ["Don't count it toward your protein target gram-for-gram."]),
            e("vitamin-k2", "Vitamin K2",
              what: "A fat-soluble vitamin involved in directing calcium into bone.",
              helps: ["May help support bone health alongside adequate calcium and vitamin D."],
              level: .limited, forms: ["Capsules (MK-7)"],
              cautions: ["Directly interacts with blood thinners (warfarin)."],
              consult: ["You take blood-thinning medication.", "You're pregnant or nursing."]),
            e("calcium", "Calcium",
              what: "The mineral your skeleton is built from; food-first is the standard advice.",
              helps: ["May help support bone health when dietary intake is consistently low."],
              level: .moderate, forms: ["Citrate", "Carbonate"],
              cautions: ["More is not better — very high supplemental intakes carry their own risks.", "Space away from iron and some antibiotics."]),
            e("glucosamine", "Glucosamine",
              what: "A compound found in cartilage, long studied for joint comfort with mixed results.",
              helps: ["May help support joint comfort for some people — study results are genuinely mixed."],
              level: .limited, forms: ["Capsules (sulfate form most studied)"],
              cautions: ["Often sourced from shellfish — allergy relevant."],
              consult: ["You have a shellfish allergy.", "You take blood thinners.", "You're pregnant or nursing."]),
            e("chondroitin", "Chondroitin",
              what: "A cartilage component usually paired with glucosamine.",
              helps: ["May help support joint comfort in some studies, often combined with glucosamine."],
              level: .limited, forms: ["Capsules"],
              cautions: ["Quality varies widely between products."]),
            e("msm", "MSM",
              what: "An organosulfur compound studied for exercise-related joint and muscle soreness.",
              helps: ["May help support joint comfort and post-exercise soreness in small studies."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["Evidence base is small and short-term."]),
            e("curcumin", "Curcumin (Turmeric Extract)",
              what: "The active pigment family in turmeric, studied for exercise recovery and joint comfort.",
              helps: ["May help support recovery from muscle-damaging exercise.", "May help support joint comfort."],
              level: .limited, forms: ["Capsules with absorption enhancers"],
              cautions: ["Poorly absorbed on its own; formulations differ a lot.", "Interacts with blood thinners."],
              consult: ["You take blood-thinning medication.", "You have gallbladder disease.", "You're pregnant or nursing."]),
        ]),
        SupplementBankGroup(name: "Gut", entries: [
            e("probiotics", "Probiotics",
              what: "Live bacterial strains; effects are strain-specific, not interchangeable.",
              helps: ["May help support digestive regularity for some people.", "Specific strains are studied for specific outcomes — a generic blend is a guess."],
              level: .limited, forms: ["Capsules", "Fermented foods"],
              cautions: ["Immunocompromised individuals should not use these without medical guidance."],
              consult: ["Your immune system is compromised.", "You have a serious GI condition.", "You're pregnant or nursing."]),
            e("psyllium", "Psyllium Husk",
              what: "A soluble fiber with one of the stronger evidence bases in the category.",
              helps: ["May help support regularity and normal cholesterol levels.", "May help support feeling full."],
              level: .strong, forms: ["Powder", "Capsules"],
              cautions: ["Increase slowly and drink plenty of water.", "Take away from medications — it can slow their absorption."]),
            e("prebiotic-fiber", "Prebiotic Fiber (Inulin / FOS)",
              what: "Fermentable fibers that feed gut bacteria.",
              helps: ["May help support a healthy gut environment when fiber intake from food is low."],
              level: .limited, forms: ["Powder"],
              cautions: ["Gas and bloating are common at first — start low."]),
            e("digestive-enzymes", "Digestive Enzymes",
              what: "Supplemental versions of enzymes your body already makes.",
              helps: ["May help support comfort after large meals for some people; lactase for lactose intolerance is the clearest case."],
              level: .limited, forms: ["Capsules"],
              cautions: ["Broad blends are poorly standardized; the specific-deficiency cases are where evidence lives."]),
            e("ginger", "Ginger",
              what: "A culinary root with a long research history for nausea.",
              helps: ["May help support settling an uneasy stomach.", "May help support post-exercise muscle soreness in small studies."],
              level: .moderate, forms: ["Capsules", "Fresh/tea"],
              cautions: ["Mild heartburn possible at higher amounts."]),
        ]),
        SupplementBankGroup(name: "Heart & Metabolic", entries: [
            e("coq10", "CoQ10",
              what: "A compound your cells use in energy production, made naturally and declining with age.",
              helps: ["May help support people on statins who experience muscle discomfort — evidence is mixed.", "May help support general cardiovascular health markers in some studies."],
              level: .limited, forms: ["Ubiquinone", "Ubiquinol softgels"],
              cautions: ["Can interact with blood thinners and blood-pressure medication."],
              consult: ["You take statins, blood thinners, or blood-pressure medication.", "You're pregnant or nursing."]),
            e("berberine", "Berberine",
              what: "A plant alkaloid studied for blood-sugar and lipid markers.",
              helps: ["May help support normal blood-sugar and cholesterol levels in studies — but it behaves like a drug, with drug-like interactions."],
              level: .moderate, forms: ["Capsules"],
              cautions: ["Meaningful interactions with diabetes medication and others.", "GI upset is common."],
              consult: ["You take ANY prescription medication — interactions are broad.", "You have diabetes.", "You're pregnant or nursing."]),
            e("plant-sterols", "Plant Sterols",
              what: "Plant compounds that compete with cholesterol absorption in the gut.",
              helps: ["May help support normal LDL cholesterol levels when used consistently with meals."],
              level: .moderate, forms: ["Softgels", "Fortified foods"],
              cautions: ["Effect is on one lab marker — not a substitute for medical management."]),
            e("alpha-lipoic-acid", "Alpha-Lipoic Acid",
              what: "An antioxidant compound involved in energy metabolism.",
              helps: ["May help support normal blood-sugar handling in some studies."],
              level: .limited, forms: ["Capsules"],
              cautions: ["Can amplify blood-sugar-lowering medication."],
              consult: ["You have diabetes or take blood-sugar medication.", "You're pregnant or nursing."]),
        ]),
        SupplementBankGroup(name: "Energy & Focus", entries: [
            e("vitamin-b12", "Vitamin B12",
              what: "A vitamin needed for red blood cells and nerves, found almost entirely in animal foods.",
              helps: ["May help support energy levels when you're actually low — common in vegan and vegetarian eating patterns.", "Does nothing extra if your levels are already normal."],
              level: .strong, forms: ["Cyanocobalamin", "Methylcobalamin"],
              cautions: ["A blood test answers this question better than guessing."]),
            e("rhodiola", "Rhodiola Rosea",
              what: "An adaptogenic herb studied for fatigue under stress.",
              helps: ["May help support perceived fatigue and mental performance during stressful stretches in small studies."],
              level: .limited, forms: ["Capsules"],
              cautions: ["Product standardization varies widely."]),
            e("l-tyrosine", "L-Tyrosine",
              what: "An amino acid precursor to dopamine and adrenaline.",
              helps: ["May help support cognitive performance under acute stress or sleep deprivation in small studies."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["Interacts with thyroid medication and MAOIs."],
              consult: ["You take thyroid medication or MAOIs.", "You're pregnant or nursing."]),
            e("alpha-gpc", "Alpha-GPC (Choline)",
              what: "A choline compound studied for cognition and power output.",
              helps: ["May help support choline intake, which most diets under-supply.", "Power-output findings are early and thin."],
              level: .limited, forms: ["Capsules", "Powder"],
              cautions: ["Long-term high-dose safety is an open research question."]),
        ]),
        SupplementBankGroup(name: "Hormonal & Women's Health", entries: [
            e("folate", "Folate",
              what: "A B-vitamin critical for cell division, with well-established guidance around pregnancy.",
              helps: ["May help support normal red-blood-cell formation.", "Public-health guidance specifically addresses intake for anyone who could become pregnant — talk to your clinician."],
              level: .strong, forms: ["Folic acid", "Methylfolate"],
              cautions: ["High supplemental folic acid can mask a B12 deficiency."],
              consult: ["You are or may become pregnant — this is a clinician conversation, not an app decision.", "You take methotrexate or seizure medication."]),
            e("iron", "Iron",
              what: "The mineral at the center of oxygen transport; deficiency is common in menstruating athletes.",
              helps: ["May help support energy and training capacity when a blood test shows you're actually low.", "Harmful in excess — this is a test-first supplement."],
              level: .strong, forms: ["Bisglycinate", "Sulfate"],
              cautions: ["Do not supplement iron without a lab result showing you need it.", "Constipation and stomach upset are common."],
              consult: ["Always — iron status should be confirmed by a blood test first.", "You have a family history of hemochromatosis."]),
            e("vitex", "Chasteberry (Vitex)",
              what: "An herb with a long traditional history for cycle-related comfort.",
              helps: ["May help support premenstrual comfort in some studies — evidence quality is modest."],
              level: .limited, forms: ["Capsules", "Tincture"],
              cautions: ["Acts on hormone signaling — not appropriate alongside hormonal medication without medical guidance."],
              consult: ["You use hormonal contraception or hormone therapy.", "You're pregnant, nursing, or trying to conceive."]),
            e("maca", "Maca Root",
              what: "A Peruvian root vegetable sold widely for energy and libido.",
              helps: ["May help support libido and mood in small, short studies; the evidence base is thin."],
              level: .limited, forms: ["Powder", "Capsules"],
              cautions: ["Marketing runs far ahead of the research here."]),
        ]),
        SupplementBankGroup(name: "Foundational", entries: [
            e("multivitamin", "Multivitamin",
              what: "A broad low-dose blend — insurance against gaps, not a performance product.",
              helps: ["May help support micronutrient intake during restricted eating (cutting, travel, picky seasons).", "Whole foods remain the better source when available."],
              level: .moderate, forms: ["Tablets", "Capsules"],
              cautions: ["Check it doesn't stack iron on top of a separate iron supplement."]),
            e("zinc", "Zinc",
              what: "A mineral involved in immune function and hormone production, lost in sweat.",
              helps: ["May help support normal immune function when intake is low — relevant for heavy sweaters and plant-based eaters."],
              level: .moderate, forms: ["Picolinate", "Citrate", "Lozenges"],
              cautions: ["Long-term high doses deplete copper.", "Take with food to avoid nausea."]),
            e("vitamin-c", "Vitamin C",
              what: "The classic antioxidant vitamin, abundant in produce.",
              helps: ["May help support normal immune function; may modestly shorten cold duration in some studies.", "Mega-doses show no extra benefit."],
              level: .moderate, forms: ["Tablets", "Powder"],
              cautions: ["Very high doses can cause GI upset and, chronically, kidney-stone risk in susceptible people."]),
            e("selenium", "Selenium",
              what: "A trace mineral involved in thyroid and antioxidant enzymes.",
              helps: ["May help support thyroid and antioxidant function when dietary intake is low — one Brazil nut a day covers most people."],
              level: .limited, forms: ["Capsules"],
              cautions: ["Narrow window — toxicity is real at not-that-high intakes. Food-first here."]),
        ]),
    ]

    static var totalCount: Int { groups.reduce(0) { $0 + $1.entries.count } }
}
